config/routes.rb
Rails.application.routes.draw do  
  # Added devise routes and overrided registration controller
  devise_for :users, :controllers => { registrations: 'registrations' }
  # hotel resources only with index route
  resources :hotel, only: :index do
    get :rooms, on: :collection
  end
  
  # Listing our all the bookings of the user
  resources :bookings, only: :index

  # Using resource hotel_categories for using the hotel_category_id for nested resources
  resources :hotel_categories, only: [] do
    # Using booking resources
    resources :bookings, only: [:new, :create] do 
      collection do
        get :search_rooms
        # route for checkig available_rooms
        get :available_rooms
      end
    end
  end

  # api routes
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      devise_for :users
      resources :hotel_rooms, only: :index
      resources :booking_informations, only: :index
    end
  end

  # root path 
  root "hotel#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
# == Schema Info
#
# Table name: bookings
#
# id                         :integer(11), not null, primary key
# check_in                   :date
# check_out                  :date
# hotel_room_id              :integer(11)
# user_id                    :integer(11)
# created_at                 :datetime, not null
# updated_at                 :datetime, not null

class Booking < ApplicationRecord
  # including validation methods
  include BookingValidations
  # callback to save booking dates with in booking dates table
  after_save :create_or_update_booking_dates
  # adding belongs to relationship with hotel_room
  belongs_to :hotel_room
  # adding belongs to relationship with user
  belongs_to :user
  # added has_many relationship with booking_dates
  has_many :booking_dates, dependent: :destroy

  # These attributes should always be present
  validates :check_in, :check_out, :hotel_room_id, :user_id, presence: true

  # Custom valudation for check in date
  # Check in date cannot be in the past
  validate :check_in_cannot_be_in_the_past

  # Custom valudation for check out date
  # Check out date should not be less than check in date
  validate :check_out_should_be_less_than_check_in

  # Custom Validation for limiting the booking for 6 months
  # Allows booking up to 6 months in advance for room reservations
  validate :check_out_cannot_be_more_than_6_months

  # Checking the hotel room availability
  validate :room_availability_check
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_hotel_category, only: [:new, :create, :available_rooms, :search_rooms]

  def new
  end

  def create
    @booking = current_user.bookings.new(booking_params)
  end

  def index
    @bookings = current_user.bookings
  end

  # Method for available rooms view
  def available_rooms
    @booking = current_user.bookings.new(booking_params)
    @hotel_rooms = @hotel_category.hotel_rooms.available_rooms(params[:booking][:check_in], params[:booking][:check_out])
  end

  # Method for search rooms view
  def search_rooms
  end

  private

  def set_hotel_category
    @hotel_category = HotelCategory.find(params[:hotel_category_id])
  end

  def booking_params
    params.require(:booking).permit(:check_in, :check_out, :hotel_room_id)
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_available_rooms.html.erb
<section id="reservation-form" class="mt50 clearfix">
  <div class="col-sm-12 col-md-4">
    <%= form_for(@booking, as: :booking, url: hotel_category_bookings_path(@hotel_category), html: {class: "reservation-vertical clearfix", remote: true}) do |f| %>
      <h2 class="lined-heading"><span>Reservation</span></h2>
      <div class="price">
        <h4><%= @hotel_category.name %></h4><br/>
       &#x20B9; <%= @hotel_category.price%>,-<span> a night</span></div>
      <div id="message"></div>
      <%= f.text_field :check_in, class: "hidden" %>
      <%= f.text_field :check_out, class: "hidden"  %>

      <div class="form-group">
        <%= f.select :hotel_room_id, @hotel_rooms.all.collect { |p| [ "Room #{p.name}", p.id ] }, {prompt: "Select Room"}, {class: "form-control"} %>      
      </div>
      <button type="submit" class="btn btn-primary btn-block">Book Now</button>
      <br/>
      <%= link_to search_rooms_hotel_category_bookings_path(@hotel_category), remote: true do %>
        < Go back and select new date range
      <% end %>
    <% end %>
  </div>
</section>

app/views/bookings/_search_rooms.html.erb
<section id="reservation-form" class="mt50 clearfix">
  <div class="col-sm-12 col-md-4">
    <%= form_tag available_rooms_hotel_category_bookings_path(@hotel_category), method: :get, class:"reservation-vertical clearfix", remote: true do %>
      <h2 class="lined-heading"><span>Reservation</span></h2>
      <div class="price">
        <h4><%= @hotel_category.name %></h4><br/>
       &#x20B9; <%= @hotel_category.price%>,-<span> a night</span></div>
      <div id="message"></div>
      <!-- Error message display -->
      <div class="form-group">
        <label for="checkin">Check-in</label>
        <div class="popover-icon" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="right" data-content="Check-In is from 11:00"> <i class="fa fa-info-circle fa-lg"> </i> </div>
        <i class="fa fa-calendar infield"></i>
        <input name="booking[check_in]" type="text" id="checkin" value="" class="form-control" placeholder="Check-in"/>
      </div>
      <div class="form-group">
        <label for="checkout">Check-out</label>
        <div class="popover-icon" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="right" data-content="Check-out is from 12:00"> <i class="fa fa-info-circle fa-lg"> </i> </div>
        <i class="fa fa-calendar infield"></i>
        <input name="booking[check_out]" type="text" id="checkout" value="" class="form-control" placeholder="Check-out"/>
      </div>
      <button type="submit" class="btn btn-primary btn-block">Search Rooms</button>
    <% end %>
  </div>
</section>

app/views/bookings/_successfully_booked.html.erb
<section id="reservation-form" class="mt50 clearfix">
  <div class="col-sm-12 col-md-4">
    <h2 class="lined-heading"><span>Reservation</span></h2>
    <div class="price">
      <h4><%= @hotel_category.name %></h4><br/>
     &#x20B9; <%= @hotel_category.price%>,-<span> a night</span></div>
    <div id="message"></div>
    <h3><i>Room <%= @booking.hotel_room.name %> has been successfully booked by you from <%= @booking.check_in.to_date %> to <%= @booking.check_out.to_date %></i></h3>

    <%= link_to bookings_path do %>
      <button type="button" class="btn btn-primary btn-block">My Bookings</button>
    <% end %>
    <br/>
    <%= link_to search_rooms_hotel_category_bookings_path(@hotel_category), remote: true do %>
      < Go back and book a new room
    <% end %>
  </div>
</section>

app/views/bookings/available_rooms.js.erb
// Validations for search filters of rooms
<% @booking.valid? %>
<% error_messages = @booking.errors.messages.slice(:check_in, :check_out) %>
<% if !error_messages.blank? %>
    errors = ""
	$.each(<%= raw error_messages.to_json %>, function(k, v) {
        $(v).each(function(){
            errors+="<li><span class='red-validation'><span class='capitalize red-validation'>"+k.replace(/_/g,' ')+"</span> "+this+"</span></li>"
        })
    });  
    $("#message").html(errors)
<% elsif @hotel_rooms.blank? %>
  $("#message").html("<span class='red-validation'>No Rooms are available in this date range.</span>")
<% else %>
  $("#message").empty()
  $("#reservation-form").replaceWith("<%= j( render 'available_rooms' )%>")
<% end %>

app/views/bookings/create.js.erb
// Validations for search filters of rooms
<% if @booking.save %>
  $("#message").empty()
  $("#reservation-form").replaceWith("<%= j( render 'successfully_booked' )%>")
<% else %>
	errors = ""
	$.each(<%= raw @booking.errors.to_json %>, function(k, v) {
        $(v).each(function(){
            errors+="<li><span class='red-validation'><span class='capitalize red-validation'>"+k.replace(/_/g,' ')+"</span> "+this+"</span></li>"
        })
    });  
    $("#message").html(errors)
<% end %>

app/views/bookings/index.html.erb
<!-- Parallax Effect -->
<script type="text/javascript">$(document).ready(function(){$('#parallax-pagetitle').parallax("50%", -0.55);});</script>

<section class="parallax-effect">
  <div id="parallax-pagetitle" style="background-image: url(/assets/parallax/parallax-01.jpg);">
    <div class="color-overlay"> 
      <!-- Page title -->
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <ol class="breadcrumb">
              <li><a href="/">Home</a></li>
              <li class="active">My Bookings</li>
            </ol>
            <h1>My Bookings</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Rooms -->
<section class="rooms mt100">
  <div class="container">
    <div class="row room-list fadeIn appear"> 
      <% if !@bookings.blank? %>
        <% @bookings.each do |booking| %>
          <!-- Room -->
          <div class="col-sm-4 category_<%= booking.hotel_room.hotel_category.id%>">
            <div class="top-of-image">
              <p><span>From <%= booking.check_in.to_date %> to <%= booking.check_out.to_date %></span></p>
              <a href="#-" class="btn btn-success btn-block">Booked by you</a> 
            </div>
            <div class="room-thumb"> <img src="/assets/rooms/room-01.jpg" alt="room 1" class="img-responsive" />
              <div class="mask">
                <div class="main">
                  <h5><%= booking.hotel_room.hotel_category.name %>, <i>Room: <%= booking.hotel_room.name %></i></h5>
                  <div class="price">&#x20B9; <%= booking.hotel_room.hotel_category.price %><span>a night</span></div>
                </div>
                <div class="content">
                  <p><span>A modern hotel room in Star Hotel</span> Nunc tempor erat in magna pulvinar fermentum. Pellentesque scelerisque at leo nec vestibulum. 
                    malesuada metus.</p>
                  <div class="row">
                    <div class="col-xs-6">
                      <ul class="list-unstyled">
                        <li><i class="fa fa-check-circle"></i> Incl. breakfast</li>
                        <li><i class="fa fa-check-circle"></i> Private balcony</li>
                        <li><i class="fa fa-check-circle"></i> Sea view</li>
                      </ul>
                    </div>
                    <div class="col-xs-6">
                      <ul class="list-unstyled">
                        <li><i class="fa fa-check-circle"></i> Free Wi-Fi</li>
                        <li><i class="fa fa-check-circle"></i> Incl. breakfast</li>
                        <li><i class="fa fa-check-circle"></i> Bathroom</li>
                      </ul>
                    </div>
                  </div>
                  <br/>
                  <b><i>Booked by you</i></b> </div>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <h2>No Bookings by you.</h2>
      <% end %>
    </div>
  </div>
</section>

app/views/bookings/new.html.erb
<!-- Parallax Effect -->
<script type="text/javascript">$(document).ready(function(){$('#parallax-pagetitle').parallax("50%", -0.55);});</script>

<section class="parallax-effect">
  <div id="parallax-pagetitle" style="background-image: url(/assets/parallax/parallax-01.jpg);">
    <div class="color-overlay"> 
      <!-- Page title -->
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <ol class="breadcrumb">
              <li><a href="/">Home</a></li>
              <li><a href="#">Room list view</a></li>
              <li class="active">Room detail</li>
            </ol>
            <h1><%= @hotel_category.name%></h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="container">
  <div class="row"> 
    <!-- Slider -->
    <section class="room-slider standard-slider mt50">
      <div class="col-sm-12 col-md-8">
        <div id="owl-standard" class="owl-carousel">
          <div class="item"> <a href="/assets/rooms/slider/room-slider-02.jpg" data-rel="prettyPhoto[gallery1]"><img src="/assets/rooms/slider/room-slider-02.jpg" alt="Bed" class="img-responsive"></a> </div>
          <div class="item"> <a href="/assets/rooms/slider/room-slider-03.jpg" data-rel="prettyPhoto[gallery1]"><img src="/assets/rooms/slider/room-slider-03.jpg" alt="Bathroom" class="img-responsive"></a> </div>
        </div>
      </div>
    </section>
    
    <!-- Reservation form -->
    <%= render 'search_rooms' %>
    
    <!-- Room Content -->
    <section>
      <div class="container">
        <div class="row">
          <div class="col-sm-7 mt50">
            <h2 class="lined-heading"><span>Room Details</span></h2>
            <h3 class="mt50">Table overview</h3>
            <table class="table table-striped mt30">
              <tbody>
                <tr>
                  <td><i class="fa fa-check-circle"></i> Double Bed</td>
                  <td><i class="fa fa-check-circle"></i> Free Internet</td>
                  <td><i class="fa fa-check-circle"></i> Free Newspaper</td>
                </tr>
                <tr>
                  <td><i class="fa fa-check-circle"></i> 60 square meter</td>
                  <td><i class="fa fa-check-circle"></i> Beach view</td>
                  <td><i class="fa fa-check-circle"></i> 2 persons</td>
                </tr>
                <tr>
                  <td><i class="fa fa-check-circle"></i> Double Bed</td>
                  <td><i class="fa fa-check-circle"></i> Free Internet</td>
                  <td><i class="fa fa-check-circle"></i> Breakfast included</td>
                </tr>
                <tr>
                  <td><i class="fa fa-check-circle"></i> Private Balcony</td>
                  <td><i class="fa fa-check-circle"></i> Flat Screen TV</td>
                  <td><i class="fa fa-check-circle"></i> Jacuzzi</td>
                </tr>
              </tbody>
            </table>
            <p class="mt50">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ligula nibh, cursus id euismod non, scelerisque nec nibh. Nam semper, ligula a rhoncus fermentum, libero lacus vulputate felis, id auctor mauris urna quis diam.</p>
          </div>
          <div class="col-sm-5 mt50">
            <h2 class="lined-heading"><span>Overview</span></h2>
            
            <!-- Nav tabs -->
            <ul class="nav nav-tabs">
              <li class="active"><a href="#overview" data-toggle="tab">Overview</a></li>
              <li><a href="#facilities" data-toggle="tab">Facilities</a></li>
              <li><a href="#extra" data-toggle="tab">Extra</a></li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
              <div class="tab-pane fade in active" id="overview">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse interdum eleifend augue, quis rhoncus purus fermentum. In hendrerit risus arcu, in eleifend metus dapibus varius. Nulla dolor sapien, laoreet vel tincidunt non, egestas non justo. Phasellus et mattis lectus, et gravida urna.</p>
                <p><img src="/assets/tab/restaurant-01.jpg" alt="food" class="pull-right"> Donec pretium sem non tincidunt iaculis. Nunc at pharetra eros, a varius leo. Mauris id hendrerit justo. Mauris egestas magna vitae nisi ultricies semper. Nam vitae suscipit magna. Nam et felis nulla. Ut nec magna tortor. Nulla dolor sapien, laoreet vel tincidunt non, egestas non justo. </p>
              </div>
              <div class="tab-pane fade" id="facilities">Phasellus sodales justo felis, a vestibulum risus mattis vitae. Aliquam vitae varius elit, non facilisis massa. Vestibulum luctus diam mollis gravida bibendum. Aliquam mattis velit dolor, sit amet semper erat auctor vel. Integer auctor in dui ac vehicula. Integer fermentum nunc ut arcu feugiat, nec placerat nunc tincidunt. Pellentesque in massa eu augue placerat cursus sed quis magna.</div>
              <div class="tab-pane fade" id="extra">Aa vestibulum risus mattis vitae. Aliquam vitae varius elit, non facilisis massa. Vestibulum luctus diam mollis gravida bibendum. Aliquam mattis velit dolor, sit amet semper erat auctor vel. Integer auctor in dui ac vehicula. Integer fermentum nunc ut arcu feugiat, nec placerat nunc tincidunt. Pellentesque in massa eu augue placerat cursus sed quis magna.</div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>

<!-- Other Rooms -->
<section class="rooms mt50">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h2 class="lined-heading"><span>Other rooms</span></h2>
      </div>
      <% HotelCategory.take(3).each do |hotel_category| %>
        <!-- Room -->
        <div class="col-sm-4">
          <div class="room-thumb"> <img src="/assets/rooms/room-01.jpg" alt="room 1" class="img-responsive" />
            <div class="mask">
              <div class="main">
                <h5><%= hotel_category.name %></h5>
                <div class="price">&#x20B9; <%= hotel_category.price %><span>a night</span></div>
              </div>
              <div class="content">
                <p><span>A modern hotel room in Star Hotel</span> Nunc tempor erat in magna pulvinar fermentum. Pellentesque scelerisque at leo nec vestibulum. 
                  malesuada metus.</p>
                <div class="row">
                  <div class="col-xs-6">
                    <ul class="list-unstyled">
                      <li><i class="fa fa-check-circle"></i> Incl. breakfast</li>
                      <li><i class="fa fa-check-circle"></i> Private balcony</li>
                      <li><i class="fa fa-check-circle"></i> Sea view</li>
                    </ul>
                  </div>
                  <div class="col-xs-6">
                    <ul class="list-unstyled">
                      <li><i class="fa fa-check-circle"></i> Free Wi-Fi</li>
                      <li><i class="fa fa-check-circle"></i> Incl. breakfast</li>
                      <li><i class="fa fa-check-circle"></i> Bathroom</li>
                    </ul>
                  </div>
                </div>
                <a href="<%= new_hotel_category_booking_path(hotel_category) %>" class="btn btn-primary btn-block">Book Now</a> </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/bookings/search_rooms.js.erb
 $("#reservation-form").replaceWith("<%= j( render 'search_rooms' )%>")
 
// Reservation Form	
//jQueryUI - Datepicker
if (jQuery().datepicker) {
    jQuery('#checkin').datepicker({
        showAnim: "drop",
        dateFormat: "yy/mm/dd",
        minDate: "-0D",
    });

    jQuery('#checkout').datepicker({
        showAnim: "drop",
        dateFormat: "yy/mm/dd",
        minDate: "-0D",
        beforeShow: function () {
            var a = jQuery("#checkin").datepicker('getDate');
            if (a) return {
                minDate: a
            }
        }
    });
    jQuery('#checkin, #checkout').on('focus', function () {
        jQuery(this).blur();
    }); // Remove virtual keyboard on touch devices
}


//Popover
jQuery('[data-toggle="popover"]').popover();